### PR TITLE
Add singularity container feature

### PR DESCRIPTION
**Pull request by shenyangshi**
A simple singularity container path fetch from python interpreter.

### CODE REVIEW

**Comment by dachengx** [comment]
I think making it too clever will cause trouble in production. Additionally, we have a mechanism to prevent the mismatch between assigned `image` and `sys.executable`: https://github.com/XENONnT/outsource/blob/aac30a1f0936e630bbde3926e0fbf065dff40c13/outsource/submitter.py#L135

In this way, I would
1. remove the default `"development"` of `image`
2. add another test in the `Submitter` to make sure that we do not use `"development"` container
3. update `README.md` by removing that TODO

**Comment by dachengx** [comment]
So I made it at https://github.com/XENONnT/outsource/pull/221.

**Comment by dachengx** [comment]
I believe a simple forbidden will prevent abuse and make sure the human processor is sober.

**Comment by dachengx** [comment]
We merged https://github.com/XENONnT/outsource/pull/221 so can close this PR. Do you agree? @shenyangshi

**Comment by shenyangshi** [comment]
Yes sounds good.

**Pull request closed without merging**
